from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtGui
from PyQt5 import QtWidgets
from PyQt5 import QtCore
import sys
from componentList import Ui_ComponentList

class Ui_PlacementLocation(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setStyleSheet("background-color: rgb(92, 53, 102);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.componentNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.componentNameLineEdit.setFont(font)
        self.componentNameLineEdit.setObjectName("componentNameLineEdit")
        self.gridLayout.addWidget(self.componentNameLineEdit, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.feederComboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.feederComboBox.setFont(font)
        self.feederComboBox.setObjectName("feederComboBox")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.feederComboBox.addItem("")
        self.gridLayout.addWidget(self.feederComboBox, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.componentNameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.componentNameLabel.setFont(font)
        self.componentNameLabel.setObjectName("componentNameLabel")
        self.gridLayout.addWidget(self.componentNameLabel, 0, 3, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(self.toggle_back)
        self.gridLayout.addWidget(self.backButton, 0, 6, 1, 1)
        self.addNewButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addNewButton.setFont(font)
        self.addNewButton.setStyleSheet("background-color: rgb(18, 127, 0);")
        self.addNewButton.setObjectName("addNewButton")
        self.addNewButton.clicked.connect(self.createNewComponent)
        self.gridLayout.addWidget(self.addNewButton, 0, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("background-color: rgb(204, 0, 0)\n"
";  \n"
"")
        self.deleteButton.setObjectName("deleteButton")
        self.deleteButton.clicked.connect(self.download_csv)
        self.deleteButton.setEnabled(False)
        self.gridLayout.addWidget(self.deleteButton, 1, 0, 1, 1)
        self.feederLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.feederLabel.setFont(font)
        self.feederLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.feederLabel.setObjectName("feederLabel")
        self.gridLayout.addWidget(self.feederLabel, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.navigationButtonHLayout = QtWidgets.QHBoxLayout()
        self.navigationButtonHLayout.setObjectName("navigationButtonHLayout")
        self.navigationsGridLayout = QtWidgets.QGridLayout()
        self.navigationsGridLayout.setObjectName("navigationsGridLayout")
        self.angleAnticlockButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.angleAnticlockButton.setFont(font)
        self.angleAnticlockButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.angleAnticlockButton.setObjectName("angleAnticlockButton")
        self.angleAnticlockButton.clicked.connect(self.thetaMinus)
        self.navigationsGridLayout.addWidget(self.angleAnticlockButton, 5, 1, 1, 1)
        self.x2MinusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.x2MinusButton.setFont(font)
        self.x2MinusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.x2MinusButton.setObjectName("x2MinusButton")
        self.x2MinusButton.clicked.connect(self.x2minus)
        self.navigationsGridLayout.addWidget(self.x2MinusButton, 2, 0, 1, 1)
        self.xPlusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.xPlusButton.setFont(font)
        self.xPlusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.xPlusButton.setObjectName("xPlusButton")
        self.xPlusButton.clicked.connect(self.xplus)
        self.navigationsGridLayout.addWidget(self.xPlusButton, 2, 3, 1, 1)
        self.yMinusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.yMinusButton.setFont(font)
        self.yMinusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.yMinusButton.setObjectName("yMinusButton")
        self.yMinusButton.clicked.connect(self.yminus)
        self.navigationsGridLayout.addWidget(self.yMinusButton, 3, 2, 1, 1)
        self.yPlusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.yPlusButton.setFont(font)
        self.yPlusButton.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.yPlusButton.setObjectName("yPlusButton")
        self.yPlusButton.clicked.connect(self.yplus)
        self.navigationsGridLayout.addWidget(self.yPlusButton, 1, 2, 1, 1)
        self.x2PlusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.x2PlusButton.setFont(font)
        self.x2PlusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.x2PlusButton.setObjectName("x2PlusButton")
        self.x2PlusButton.clicked.connect(self.x2plus)
        self.navigationsGridLayout.addWidget(self.x2PlusButton, 2, 4, 1, 1)
        self.angleClockButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.angleClockButton.setFont(font)
        self.angleClockButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.angleClockButton.setObjectName("angleClockButton")
        self.angleClockButton.clicked.connect(self.thetaPlus)
        self.navigationsGridLayout.addWidget(self.angleClockButton, 5, 3, 1, 1)
        self.y2MinusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.y2MinusButton.setFont(font)
        self.y2MinusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.y2MinusButton.setObjectName("y2MinusButton")
        self.y2MinusButton.clicked.connect(self.y2minus)
        self.navigationsGridLayout.addWidget(self.y2MinusButton, 4, 2, 1, 1)
        self.y2PlusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.y2PlusButton.setFont(font)
        self.y2PlusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.y2PlusButton.setObjectName("y2PlusButton")
        self.y2PlusButton.clicked.connect(self.y2plus)
        self.navigationsGridLayout.addWidget(self.y2PlusButton, 0, 2, 1, 1)
        self.angleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.angleLabel.setFont(font)
        self.angleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.angleLabel.setObjectName("angleLabel")
        self.navigationsGridLayout.addWidget(self.angleLabel, 5, 2, 1, 1)
        self.xMinusButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.xMinusButton.setFont(font)
        self.xMinusButton.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"\n"
"")
        self.xMinusButton.setObjectName("xMinusButton")
        self.xMinusButton.clicked.connect(self.xminus)
        self.navigationsGridLayout.addWidget(self.xMinusButton, 2, 1, 1, 1)
        self.xyLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.xyLabel.setFont(font)
        self.xyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xyLabel.setObjectName("xyLabel")
        self.navigationsGridLayout.addWidget(self.xyLabel, 2, 2, 1, 1)
        self.navigationButtonHLayout.addLayout(self.navigationsGridLayout)
        self.liveViewVerticalLayout = QtWidgets.QVBoxLayout()
        self.liveViewVerticalLayout.setObjectName("liveViewVerticalLayout")
        self.liveViewLabel = QtWidgets.QLabel(self.centralwidget)
        self.liveViewLabel.setObjectName("liveViewLabel")
        self.liveViewVerticalLayout.addWidget(self.liveViewLabel)
        self.coordiHorizontalLayout = QtWidgets.QHBoxLayout()
        self.coordiHorizontalLayout.setObjectName("coordiHorizontalLayout")
        self.xLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xLabel.setFont(font)
        self.xLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xLabel.setObjectName("xLabel")
        self.coordiHorizontalLayout.addWidget(self.xLabel)
        self.x1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x1Label.setFont(font)
        self.x1Label.setObjectName("x1Label")
        self.coordiHorizontalLayout.addWidget(self.x1Label)
        self.yLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yLabel.setFont(font)
        self.yLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yLabel.setObjectName("yLabel")
        self.coordiHorizontalLayout.addWidget(self.yLabel)
        self.y1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y1Label.setFont(font)
        self.y1Label.setObjectName("y1Label")
        self.coordiHorizontalLayout.addWidget(self.y1Label)
        self.zLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zLabel.setFont(font)
        self.zLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zLabel.setObjectName("zLabel")
        self.coordiHorizontalLayout.addWidget(self.zLabel)
        self.z1Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.z1Label.setFont(font)
        self.z1Label.setObjectName("z1Label")
        self.coordiHorizontalLayout.addWidget(self.z1Label)
        self.liveViewVerticalLayout.addLayout(self.coordiHorizontalLayout)
        self.navigationButtonHLayout.addLayout(self.liveViewVerticalLayout)
        self.verticalLayout_2.addLayout(self.navigationButtonHLayout)
        self.lowerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.lowerHorizontalLayout.setObjectName("lowerHorizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowerHorizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowerHorizontalLayout.addItem(spacerItem3)
        self.saveLocationButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.saveLocationButton.setFont(font)
        self.saveLocationButton.setObjectName("saveLocationButton")
        self.saveLocationButton.clicked.connect(self.saveLocation)
        self.lowerHorizontalLayout.addWidget(self.saveLocationButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lowerHorizontalLayout.addItem(spacerItem4)
        self.lowerHorizontalLayout.setStretch(0, 25)
        self.lowerHorizontalLayout.setStretch(1, 25)
        self.lowerHorizontalLayout.setStretch(2, 10)
        self.lowerHorizontalLayout.setStretch(3, 12)
        self.verticalLayout_2.addLayout(self.lowerHorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.feederComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.feederComboBox.setItemText(1, _translate("MainWindow", "2"))
        self.feederComboBox.setItemText(2, _translate("MainWindow", "3"))
        self.feederComboBox.setItemText(3, _translate("MainWindow", "4"))
        self.feederComboBox.setItemText(4, _translate("MainWindow", "5"))
        self.feederComboBox.setItemText(5, _translate("MainWindow", "6"))
        self.feederComboBox.setItemText(6, _translate("MainWindow", "7"))
        self.feederComboBox.setItemText(7, _translate("MainWindow", "8"))
        self.feederComboBox.setItemText(8, _translate("MainWindow", "9"))
        self.feederComboBox.setItemText(9, _translate("MainWindow", "10"))
        self.feederComboBox.setItemText(10, _translate("MainWindow", "11"))
        self.feederComboBox.setItemText(11, _translate("MainWindow", "12"))
        self.feederComboBox.setItemText(12, _translate("MainWindow", "13"))
        self.feederComboBox.setItemText(13, _translate("MainWindow", "14"))
        self.feederComboBox.setItemText(14, _translate("MainWindow", "15"))
        self.componentNameLabel.setText(_translate("MainWindow", "Component Name"))
        self.backButton.setText(_translate("MainWindow", "<-"))
        self.addNewButton.setText(_translate("MainWindow", "Add new "))
        self.deleteButton.setText(_translate("MainWindow", "Download CSV"))
        self.feederLabel.setText(_translate("MainWindow", "Feeder "))
        self.angleAnticlockButton.setText(_translate("MainWindow", "<"))
        self.x2MinusButton.setText(_translate("MainWindow", "<<"))
        self.xPlusButton.setText(_translate("MainWindow", ">"))
        self.yMinusButton.setText(_translate("MainWindow", "\\/"))
        self.yPlusButton.setText(_translate("MainWindow", "/\\"))
        self.x2PlusButton.setText(_translate("MainWindow", ">>"))
        self.angleClockButton.setText(_translate("MainWindow", ">"))
        self.y2MinusButton.setText(_translate("MainWindow", "\\/"))
        self.y2PlusButton.setText(_translate("MainWindow", "/\\"))
        self.angleLabel.setText(_translate("MainWindow", "θ"))
        self.xMinusButton.setText(_translate("MainWindow", "<"))
        self.xyLabel.setText(_translate("MainWindow", "X/Y"))
        self.liveViewLabel.setText(_translate("MainWindow", "live View"))
        self.xLabel.setText(_translate("MainWindow", "X:"))
        self.x1Label.setText(_translate("MainWindow", "0"))
        self.yLabel.setText(_translate("MainWindow", "Y:"))
        self.y1Label.setText(_translate("MainWindow", "0"))
        self.zLabel.setText(_translate("MainWindow", "Z:"))
        self.z1Label.setText(_translate("MainWindow", "0"))
        self.saveLocationButton.setText(_translate("MainWindow", "Save Location"))

